

export enum I18n {
    INFO_SUCCESS = 'OK',
    ERR_SERVICE_NOT_INITIALIZED = 'E_SERVICE_NOT_INITIALIZED',
    ERR_DELIVERY_INVALID = 'E_DELIVERY_INVALID',
    WARN_VAL_FILE_EXIST = 'W_VAL_FILE_EXIST',
    WARN_VAL_WRONG_FILETYPE = 'W_VAL_WRONG_FILETYPE',
    WARN_VAL_INVALID_PARAMS = 'W_VAL_INVALID_PARAMS',
    WARN_USER_NOT_FOUND = 'W_USER_NOT_FOUND',
    WARN_USER_PASSWORD_WRONG = 'W_USER_PASSWORD_WRONG',
    WARN_TOKEN_NOT_PROVIDED = 'W_TOKEN_NOT_PROVIDED',
    WARN_TOKEN_WRONG = 'W_TOKEN_WRONG',
    WARN_DELIVERY_PICKDATE_PROVIDED = 'W_DELIVERY_PICKDATE_PROVIDED',
    WARN_STATION_NOT_FOUND = 'W_STATION_NOT_FOUND',
    WARN_STATION_LOCKER_NOT_FOUND = 'W_STATION_LOCKER_NOT_FOUND',
    WARN_STATION_LOCKER_BUSY = 'W_STATION_LOCKER_BUSY',
    WARN_INVALID_PARAMS = 'W_INVALID_PARAMS'
}
